# Generated by Django 5.1 on 2024-09-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0002_dairbag_is_deleted_dmold_is_deleted_dpcb_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dairbag',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='dmold',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='dpcb',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='dpinarrival',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='dreelpackaging',
            name='is_deleted',
        ),
    ]
