# Generated by Django 5.0.8 on 2024-09-27 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0009_dpcb_d_pcb_machine_6ecc84_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='msis_app.machine'),
        ),
    ]
