# Generated by Django 5.0.8 on 2024-10-14 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0011_camera_cameras_machine_795ef2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='camera',
            name='cameras_machine_795ef2_idx',
        ),
        migrations.RemoveIndex(
            model_name='camera',
            name='cameras_is_dele_3f45cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='dmold',
            name='d_mold_machine_2aea5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='dmold',
            name='d_mold_camera__c6e7cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='dmold',
            name='d_mold_timesta_2286bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='dmold',
            name='d_mold_status_c2dee3_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='machines',
        ),
        migrations.AddField(
            model_name='camera',
            name='factory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_cameras', to='msis_app.factory'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['machine', 'is_deleted', 'factory'], name='cameras_machine_cf8f84_idx'),
        ),
        migrations.AddIndex(
            model_name='dmold',
            index=models.Index(fields=['machine', 'camera', 'timestamp', 'status'], name='d_mold_machine_ea17be_idx'),
        ),
    ]
