# Generated by Django 5.0.8 on 2024-10-16 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0015_alter_category_options_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='machine',
            name='machines_name_a61b35_idx',
        ),
        migrations.AddField(
            model_name='machine',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_category', to='msis_app.category'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['name', 'factory', 'is_deleted', 'category'], name='machines_name_90d870_idx'),
        ),
    ]
