# Generated by Django 4.2.16 on 2024-10-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0016_remove_machine_machines_name_a61b35_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='reset_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
