# Generated by Django 5.1.2 on 2024-11-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0017_machine_last_reset_category_machine_last_reset_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='last_reset_category',
        ),
    ]
