# Generated by Django 4.2.16 on 2024-11-01 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0018_merge_20241101_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='reset_timestamp',
        ),
    ]
