# Generated by Django 5.0.8 on 2024-11-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0018_remove_machine_last_reset_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttClientState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'mqtt_client_state',
            },
        ),
    ]
