# Generated by Django 4.2.16 on 2024-11-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0019_remove_factory_reset_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_reset_machine_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
