# Generated by Django 5.0.8 on 2024-11-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0019_mqttclientstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttclientstate',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
