# Generated by Django 4.2.16 on 2024-11-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0020_mqttclientstate_last_updated'),
        ('msis_app', '0021_rename_last_reset_machine_name_machine_last_reset_machine'),
    ]

    operations = [
    ]
