# Generated by Django 5.1.3 on 2024-11-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0022_merge_20241107_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_reset_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
