# Generated by Django 5.0.8 on 2024-09-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0005_dmold_d_mold_machine_2aea5b_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dpinarrival',
            index=models.Index(fields=['machine'], name='d_pin_arriv_machine_c66a22_idx'),
        ),
        migrations.AddIndex(
            model_name='dpinarrival',
            index=models.Index(fields=['camera'], name='d_pin_arriv_camera__4471d5_idx'),
        ),
        migrations.AddIndex(
            model_name='dpinarrival',
            index=models.Index(fields=['timestamp'], name='d_pin_arriv_timesta_675bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='dpinarrival',
            index=models.Index(fields=['status'], name='d_pin_arriv_status_a360c0_idx'),
        ),
    ]
