# Generated by Django 5.0.8 on 2024-09-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0006_dpinarrival_d_pin_arriv_machine_c66a22_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dairbag',
            index=models.Index(fields=['machine'], name='d_airbag_machine_2ea8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='dairbag',
            index=models.Index(fields=['camera'], name='d_airbag_camera__ebbfd3_idx'),
        ),
        migrations.AddIndex(
            model_name='dairbag',
            index=models.Index(fields=['timestamp'], name='d_airbag_timesta_bea790_idx'),
        ),
        migrations.AddIndex(
            model_name='dairbag',
            index=models.Index(fields=['status'], name='d_airbag_status_07e0f8_idx'),
        ),
    ]
