# Generated by Django 5.0.8 on 2024-09-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0007_dairbag_d_airbag_machine_2ea8ff_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dreelpackaging',
            index=models.Index(fields=['machine'], name='d_reel_pack_machine_19da5d_idx'),
        ),
        migrations.AddIndex(
            model_name='dreelpackaging',
            index=models.Index(fields=['camera'], name='d_reel_pack_camera__accecf_idx'),
        ),
        migrations.AddIndex(
            model_name='dreelpackaging',
            index=models.Index(fields=['timestamp'], name='d_reel_pack_timesta_588f93_idx'),
        ),
        migrations.AddIndex(
            model_name='dreelpackaging',
            index=models.Index(fields=['status'], name='d_reel_pack_status_0d6410_idx'),
        ),
    ]
