# Generated by Django 5.0.8 on 2024-09-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('msis_app', '0010_alter_camera_machine'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['machine'], name='cameras_machine_795ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['is_deleted'], name='cameras_is_dele_3f45cb_idx'),
        ),
        migrations.AddIndex(
            model_name='factory',
            index=models.Index(fields=['name'], name='factories_name_5d066a_idx'),
        ),
        migrations.AddIndex(
            model_name='factory',
            index=models.Index(fields=['is_deleted'], name='factories_is_dele_805252_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['name'], name='machines_name_77122a_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['factory'], name='machines_factory_8a5607_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['is_deleted'], name='machines_is_dele_c0650e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted'], name='users_is_dele_21b557_idx'),
        ),
    ]
