# Generated by Django 4.2.16 on 2024-11-01 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0017_factory_reset_timestamp'),
        ('msis_app', '0017_machine_last_reset_category_machine_last_reset_time'),
    ]

    operations = [
    ]
