# Generated by Django 4.2.16 on 2024-11-01 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msis_app', '0020_machine_last_reset_machine_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='last_reset_machine_name',
            new_name='last_reset_machine',
        ),
    ]
